---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
library(request)
```

```{r}


baseurl = 'https://s5phub.copernicus.eu/dhus/odata/v1/Products'
count_path ='dhus/odata/v1/Products/$count'
query_path = 'dhus/odata/v1/Products/'

parameter_list <- list(    
    `$filter` = "substringof('NO2',Name) and year(ContentDate/End) eq 2020 and month(ContentDate/End) le 3"
    )

count_resp <- GET(
  modify_url(baseurl, path = count_path), 
  query = parameter_list,
  authenticate("s5pguest", "s5pguest")
  )
results_count <- content(count_resp)
results_count

query_resp = GET(
  modify_url(baseurl, path = query_path), 
  authenticate("s5pguest", "s5pguest"),
  query = append(parameter_list, list(`$format` = 'text/csv'))
  )
query_csv <- content(query_resp)
query_csv

NO2_retreive <- function(skip_count = 0L, query_params = parameter_list) {
  query_params <- append(query_params,list(`$skip` = skip_count, `$format` = 'text/csv'))
  query_resp = GET(
    modify_url(baseurl, path = query_path), 
    authenticate("s5pguest", "s5pguest"),
    query = query_params
  )
  return(content(query_resp))
}

# Prepare base for loop
NO2_resp = NO2_retreive()
NO2_tbl = NO2_resp
counter = nrow(NO2_tbl)

# Retrieve all IDs that match filter by adjusting skipcounter until it's not equal to 50
while (nrow(NO2_resp) == 50) {
  
  NO2_resp = NO2_retreive(skip_count = counter)
  NO2_tbl <- bind_rows(
    NO2_tbl,
    NO2_resp
    )
  counter = counter + 50
  Sys.sleep(0.5) #Being nice to server
  print(paste("Fetched",nrow(NO2_tbl),"results out of", results_count))
}
NO2_tbl
```

```{r}
NO2_tbl %>% 
  mutate(downloadURL = modify_url(baseurl, path = paste0(query_path,'(',Id,')')))
  write_csv("NO2_URL_list.csv")
```

```{r}
count_url = 'https://s5phub.copernicus.eu/dhus/odata/v1/Products/$count?$filter=substringof(%27L2__NO2%27,Name)%20and%20year(ContentDate/End)%20eq%202020%20and%20month(ContentDate/End)%20le%203&$orderby=ContentDate/End%20desc' %>% 

'https://s5phub.copernicus.eu/dhus/odata/v1/Products/$count?$filter=substringof(%27L2__NO2%27,Name)%20and%20year(ContentDate/End)%20eq%202020%20and%20month(ContentDate/End)%20le%203&$orderby=ContentDate/End%20desc' %>% request::api() 

url <- modify_url("https://api.github.com", param = )
params = list(    
    `$format` = 'text/csv',
    `$filter` = "substringof('NO2',Name) and year(ContentDate/End) eq 2020 and month(ContentDate/End) le 3",
    `$inlinecount` = 'allpages',
    `$skip` = as.integer(skip_count)
)
  
```

```{r}
a = 'https://s5phub.copernicus.eu/dhus/odata/v1/Products/$count' %>% 
  api_simple_auth(user = "s5pguest", pwd = "s5pguest", type = "basic") %>% 
  api_query(.dots = params)
a$d$results[[1]]$Name
```


