---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

https://notes.stefanomattia.net/2018/02/14/Plotting-Sentinel-5P-NetCDF-products-with-R-and-ggplot2/
```{r}
library(chron)
library(RColorBrewer)
library(lattice)
library(ncdf4)
library(tidyverse)
library(RSQLite)
library(DBI)
library(feather)
library(RMariaDB)

library(reticulate)
use_python("/usr/local/bin/python3", required = TRUE)
```

Things that need ot be extracted (WIP)
+ Tracking ID
+ id
+ Time Coverage Start
+ Time Coverage End 
+ nitrogendioxide_total_column

```{r functions}
# Function that takes in any function as input and runs the function while supress printing messages
quiet <- function(x) { 
  sink(tempfile()) 
  on.exit(sink()) 
  invisible(force(x)) 
}

# Function that Reads in connection to .nc file and outputs relevant data in tibble format
nc_extract_no2dat <- function(nc_conn) {
  # Get Relevant File attribtues
  nc_attr <- quiet(ncatt_get(nc_conn,0)) %>% as_tibble() %>% select(tracking_id,id,time_coverage_start,time_coverage_end)
  # List relevant variables to extract
  varnames <- c(
    "DETAILED_RESULTS/nitrogendioxide_stratospheric_column",
    "DETAILED_RESULTS/nitrogendioxide_stratospheric_column_precision" ,
    "DETAILED_RESULTS/nitrogendioxide_total_column",
    "DETAILED_RESULTS/nitrogendioxide_total_column_precision",
    # "DETAILED_RESULTS/nitrogendioxide_total_column_precision_kernel",
    # "DETAILED_RESULTS/nitrogendioxide_slant_column_density",
    # "DETAILED_RESULTS/nitrogendioxide_slant_column_density_precision",
    "PRODUCT/latitude",
    "PRODUCT/longitude"
    )
  # Bind Variable Data together 
  vardat <-  varnames %>% map(ncvar_get,nc = nc_conn) %>% map(as.vector) %>% map(tibble) %>% bind_cols() 
  names(vardat) <- varnames 
  
  # Filter out columns without any NO2 data and Join Variable Data with File attirbutes
  nc_dat_tbl <- vardat %>% filter_at(vars(starts_with("DETAILED_")),any_vars(!is.na(.))) %>% merge(nc_attr)
  return(nc_dat_tbl)
}
```

# Data Import 
```{r}
fname <- "../data/S5P_OFFL_L2__NO2____20200105T112716_20200105T130846_11550_01_010302_20200107T042413"
nc <- nc_open(fname)
ncdat <- nc_extract_no2dat(nc)

fname2 <- "../data/S5P_OFFL_L2__NO2____20200119T203333_20200119T221503_11754_01_010302_20200124T140330.zip"
nc2 <- nc_open(fname2)
ncdat2 <- nc_extract_no2dat(nc2)
```

# Data Collect
Read through nc files, filter out data within specified region, and save results to SQL db. 
```{r WA Insert To DB}
# Connect to Database
no2db <- dbConnect(
  RMariaDB::MariaDB(), 
  user = rstudioapi::askForPassword("Database user"),
  password = rstudioapi::askForPassword("Database password"),
  dbname = db, 
  port = dbport,
  host = localhost)

# Find feather files (converted from .nc files in python) 
feather_path = "/Volumes/pathtofeatherfiles/"
feather_fnames = list.files(feather_path,full.names = TRUE) %>% str_subset("feather")

# Create table with template columns
no2dat <- feather_fnames %>% 
  first %>% 
  read_feather() %>% 
  slice(0)
# Create table within database
dbWriteTable(no2db, "WA_NO2", no2dat,overwrite = TRUE)
dbReadTable(no2db, "WA_NO2")
dbListTables(no2db)

# loop through each file and append to database
for (fname in feather_fnames) {
    cat("Opening :",which(feather_fnames == fname),"of",length(feather_fnames))
    feath_dat <- read_feather(fname) %>% 
    filter(
      between(lats, 35,55),
      between(lons, -135,-110)
    )
    cat(" --",nrow(feath_dat), "results!")
    dbAppendTable(no2db,"WA_NO2",feath_dat)
    cat(" --","Appended! \n")
}

```
 
 


```{r Collect WA subset}
# Obtain slice of data from DB
week1dat <- tbl(no2db, "WA_NO2") %>% 
  # filter(id %in% test_days) %>%
  filter(str_detect(id,"202001")) %>%
  # mutate(time_coverage_end = as.Date(time_coverage_end))
  collect()
```


# Visualize
```{r }
# Function for plotting modified from blog
PlotRegion <- function(df_sub, title = "NO2 Concentration in WA") {
  # Plot the given dataset over a geographic region.
  #
  # Args:
  #   df: The dataset, should include the no2tc, lat, lon columns
  #   latlon: A vector of four values identifying the botton-left and top-right corners
  #           c(latmin, latmax, lonmin, lonmax)
  #   title: The plot title

  # subset the data frame first
  # df_sub <- subset(df, no2tc!=fillvalue & lat>latlon[1] & lat<latlon[2] & lon>latlon[3] & lon<latlon[4])
  # df_sub <- df_sub %>% filter(!is.na(no2))
  subtitle = paste("Data min =", formatC(min(df_sub$no2, na.rm=T), format="e", digits=2),
                   "max =", formatC(max(df_sub$no2, na.rm=T), format="e", digits=2))

  ggplot(df_sub, aes(y=lats, x=lons, fill=no2)) +
    geom_tile(width=1, height=1) +
    borders('world', xlim=range(df_sub$lons), ylim=range(df_sub$lats),
            colour='gray90', size=.2) +
    theme_light() +
    theme(panel.ontop=TRUE, panel.background=element_blank()) +
    scale_fill_distiller(palette='Spectral',
                         limits = c(1.024826e-05  ,0.0007860105 )) +
                         # limits=c(quantile(df_sub$no2, .7, na.rm=T),
                         #          quantile(df_sub$no2, .999, na.rm=T))) +
    coord_quickmap(xlim=c(-127, -117), ylim=c(43, 53)) +
    labs(title=df_sub$time_coverage_end %>% first, subtitle=subtitle,
         x="Longitude", y="Latitude" )#,
         # fill=expression(molecules~cm^-2))
  }
# eu.coords = c(34, 60, -15, 35)
week1dat$no2 %>% min(na.rm = T)
week1dat %>% 
  mutate(time_coverage_end = as.Date(time_coverage_end)) %>% 
  group_by(time_coverage_end) %>% 
  group_split() %>% 
  # .[4:30] %>%
  map(PlotRegion)
# stars::cur
```


```{python}
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
from datetime import date
import os
print("hello")
```

```{r source}
library(reticulate)
use_python("/usr/local/bin/python3", required = TRUE)
pypath = "/Users/etiowousoro/Documents/Analytics/thea/scripts/s5p_analyze.py"
# source_python(pypath)

make_no2viz <- function(no2_dataframe) {
  no2_dataframe = no2_dataframe %>% 
    rename(no2 = `value`, lats = latitude, lons = longitude)
  no2_dataframe %>% 
  ggplot( aes(y=lats, x=lons, fill=no2)) +
    geom_tile(width=1, height=1) +
    scale_fill_distiller(palette='Spectral') + 
    borders('world', 
            xlim=range(as.numeric(no2_dataframe$lons)),
            ylim=range(as.numeric(no2_dataframe$lats)),
            colour='gray90', size=.2) +
    theme_light() +
    theme(panel.ontop=TRUE, panel.background=element_blank()) +
    scale_fill_distiller(palette='Spectral',) +
                         # limits = c(1.024826e-05  ,0.0007860105 )) +
                         # limits=c(quantile(df_sub$no2, .7, na.rm=T),
                         #          quantile(df_sub$no2, .999, na.rm=T))) +
    coord_quickmap(xlim=c(-127, -117), ylim=c(43, 53)) +
    labs(title=no2_dataframe$time_coverage_end %>% first, subtitle=no2_dataframe$tracking_id %>% first,
         x="Longitude", y="Latitude" )#,
}
library(sf)
# library(rnaturalearth)

make_no2viz(datafiltered)
make_no2viz(dataraw)
```


```{r}
zippath <- "../data/"
zippath %>% 
  list.files(full.names = TRUE) %>% 
  str_subset("zip") %>% 
  # first %>% 
  map(nc_open) %>% 
  map(nc_extract_no2dat) %>% 
  map(make_no2viz)
  
  
nc2 <- nc_open(fname2)
ncdat2 <- nc_extract_no2dat(nc2)
# ncdat2 %>% 
make_no2viz <- function(no2_dataframe) {
  no2_dataframe %>% 
  rename(no2 = `DETAILED_RESULTS/nitrogendioxide_total_column`, lats = `PRODUCT/latitude`, lons = `PRODUCT/longitude`) %>%  
  ggplot( aes(y=lats, x=lons, fill=no2)) +
    geom_tile(width=1, height=1) +
    scale_fill_distiller(palette='Spectral') + 
    borders('world', 
            xlim=range(as.numeric(no2_dataframe$`PRODUCT/longitude`)),
            ylim=range(as.numeric(no2_dataframe$`PRODUCT/latitude`)),
            colour='gray90', size=.2) +
    theme_light() +
    theme(panel.ontop=TRUE, panel.background=element_blank()) +
    scale_fill_distiller(palette='Spectral',
                         limits = c(1.024826e-05  ,0.0007860105 )) +
                         # limits=c(quantile(df_sub$no2, .7, na.rm=T),
                         #          quantile(df_sub$no2, .999, na.rm=T))) +
    coord_quickmap(xlim=c(-127, -117), ylim=c(43, 53)) +
    labs(title=no2_dataframe$time_coverage_end %>% first, subtitle=no2_dataframe$tracking_id %>% first,
         x="Longitude", y="Latitude" )#,
}
```

